### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by LiUzHiAn** [StevenLei2017/AI_Projects#1]
Hi, @StevenLei2017 

感谢分享，非常棒的工作 👍 👍 👍 

在训练模型的时候，保存训练数据类别名称的文件应该是`voc_classes.txt`吧，你在readme中写成了`voc_names.txt`了，应该是个笔误。还有就是，需要安装matplotlib库。

**Comment by leikunx** [comment]
以后提issues的读者注意，可以这样说：文章001的第2.2节，...
都是直接用anaconda，里面自带各种库，matplotlib库根本不用操心的。
这篇文章直接从我的简书复制过来的，没有对github做响应的修改，感觉还不是很完美。

**Comment by leikunx** [comment]
我已经重写了工程001的readme.md文档，使其更符合github网站的格式，读者能够快速复现。
