### ISSUE TITLE
玩的真花哨，既然用了tf架构的人脸检测，还去用mxnet的人脸识别，这是干什么？直接用别人的模型？？

### ISSUE THREAD

**Issue by Danbinabo** [StevenLei2017/AI_Projects#3]

**Comment by leikunx** [comment]
insightFace是现在人脸身份判别开源模型中效果最好的，它的原版就是mxnet。我搞懂mxnet版本的insightFace，再把它利用起来，这本身并没有什么问题。如何使用别人的模型，本来就是一种宝贵的经验，我认为这是值得分享的事情。只要有一个人需要我去分享如何使用模型，我就会坚持做这件事情。
