### ISSUE TITLE
关于005_模型部署中resources的一些疑问

### ISSUE THREAD

**Issue by HYY001** [StevenLei2017/AI_Projects#4]
模型部署这块我基本上跑完了，结果也差不多。
不过对于resources中的文件，有一些疑问。
FilaMono-Medium.otf
cifar10_ResNet56v2_model.162.h5
pixel_mean.pickle
这三个文件分别是什么呢，需要自己根据自己模型生成的吗

**Comment by leikunx** [comment]
otf文件是字体文件，h5是keras训练模型保存的权重，pixel_mean.pickles是32 * 32的像素矩阵上的均值。resources/readme.md中有b站视频链接，就是讲解这些内容的。

**Comment by HYY001** [comment]
好的，我会去看看的
