### ISSUE TITLE
insightface里的2_demo.py怎么保存加载的数据,否则人脸库有几千张时每次启动都要加载非常久

### ISSUE THREAD

**Issue by gclsoft** [StevenLei2017/AI_Projects#7]
我的硬件环境（如果你觉得有必要的话），我的软件环境（操作系统型号 win7、python版本 3.6、各种库版本等）
我在复现第007_人脸识别实践_mxnet版insightFace 的第2步时遇到了问题
我遇到的问题：
我把lfw的数据都加入了人脸库了, 一启动2_demo.py加载会耗时3个小时,怎么保存成文件,下次直接加载这个文件就行?

**Comment by leikunx** [comment]
使用pickle库实现数据的持久化
